"use strict";
var number = 20;
var djisktra = 2 ^ 53;
var string = "hello";
var boolean = true;
var objectArray = ["item", number, 12.2398, false, [1, 2, 3], 'a'];
var object = { key1: "Value", number: 13, "Juan Perez": true };
var indefinido = undefined;
var nulo = null;
console.log(typeof number);
console.log(typeof djisktra);
console.log(typeof string);
console.log(typeof boolean);
console.log(typeof objectArray);
console.log(typeof object);
console.log(typeof indefinido);
console.log(typeof nulo);
var number1;
var cadena;
var booleano;
var arreglo;
var objetos;
